### ISSUE TITLE
v.1.5.3 is broken

### ISSUE THREAD

**Issue by Hirbod** [EddyVerbruggen/cordova-plugin-safariviewcontroller#106]
@EddyVerbruggen 

`Can't find variable: SafariViewController`

Reverted back to 1.5.2 and it works as expected.

iPhone X (real Device)
Version 1.5.3
iOS 11.2.6

**Comment by larssn** [comment]
1.5.3 works for me. Doing a simple `cordova plugin add cordova-plugin-safariviewcontroller`.

Could you check the browser console for the variable.

**Comment by Hirbod** [comment]
I did, used the Safari Debugger, ends up with the error posted in the first thread.
1.5.2 works flawlessly

**Comment by WuglyakBolgoink** [comment]
@Hirbod  are u fixed?

**Comment by Hirbod** [comment]
Problem was caused bei Ionic Webview

**Comment by WuglyakBolgoink** [comment]
Hallo @Hirbod can u write what was exactly too?

**Comment by Hirbod** [comment]
Version 2 of Ionic Webview is not compatible, thats all I know for now. As soon as I install it, plugins won't be loaded
