### ISSUE TITLE
Android Studio no tind method jacjOptions

### ISSUE THREAD

**Issue by htsnet** [EddyVerbruggen/cordova-plugin-safariviewcontroller#107]
I am returning to an existent  app to do one maintenance. When I try to build with Android Studio 3.1 I am receiving this message error:

Could not find method jackOptions() for arguments [politicustwitter_SafariViewCon_6wdsos46ekmbzaj9qtadbam54$_run_closure1$_closure2$_closure3$_closure5@6c9b27c2] on DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=30000, versionName=null, applicationId=br.com.htsnet.politicustwitter, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.

When I removed this plugin, the build was OK. Then, I added again this plugin and the message reappeared.

What it means? What I need to do?

**Comment by urlless** [comment]
+1

**Comment by larssn** [comment]
@urlless, use the thumbs up feature 👍
