### ISSUE TITLE
Could SFSafariViewController replace UIWebView (or WkWebView respectively)?

### ISSUE THREAD

**Issue by ChristianWeyer** [EddyVerbruggen/cordova-plugin-safariviewcontroller#111]
Hey there,

Could this plugin also be used to entirely replace UIWebView as the default webview in Cordova?
Just like https://github.com/ionic-team/cordova-plugin-ionic-webview does for WkWebView?

Reason: Only SFSafariViewController seems to support Service Workers today (https://webkit.org/blog/8090/workers-at-your-service/).

Thanks!

**Comment by EddyVerbruggen** [comment]
Nope.

**Comment by larssn** [comment]
This plugin is for managing popups basically.

Suggest you stick with WkWebView, either the ionic one, or the cordova one.
