### ISSUE TITLE
Logout using Auth2.0

### ISSUE THREAD

**Issue by matteobortolazzo** [EddyVerbruggen/cordova-plugin-safariviewcontroller#113]
Hi, I'm using Azure AD B2C for authentication (grant code flow). 
After the first login, every time I try to log in the page login automatically and this is a problem if I want to change user. Is there a way to clear the safari view cache/cockies? Thanks

**Comment by larssn** [comment]
This is sadly not supported at the moment. Haven't looked into the code to see if it's something the native API's support.

**Comment by matteobortolazzo** [comment]
Ok no problem, auth cookies last 24h (and I can set 15min) so logout works correctly after that period. Thanks
