### ISSUE TITLE
Feature request: block ability to share/copy or open in Safari/Chrome current link

### ISSUE THREAD

**Issue by Gidemin** [EddyVerbruggen/cordova-plugin-safariviewcontroller#138]
Hi. I'm using this plugin for displaying some content and I face cases when I need to block the ability for share opened link(copy URL, share it by browser tools or open URL in Safari/Chrome). As I know, Chrome custom tabs have tools to deprecate sharing the opened URL. Unfortunately, can't say something about Safari or WKWebView (I don't have experience in develope for iOS)

So, I think it's gonna be a good feature for improving plugin functionality and security improving.

Thanks for attention.

**Comment by EddyVerbruggen** [comment]
Please Google if that's possible with SafariViewController. If so, it will be possible with this plugin as well, so reopen with a link to your findings.
