### ISSUE TITLE
[phonegap] [console.error] Error: Can't find variable: SafariViewController

### ISSUE THREAD

**Issue by davibertolini** [EddyVerbruggen/cordova-plugin-safariviewcontroller#14]
Hello, I'm a bit embarrassed this question is not an issue of the plugin, but an issue I don't know how to use it. I installed the plugin, but calling the openUrl() function throws this error:

`Error: Can't find variable: SafariViewController`

Furthermore, my IDE (WebStorm 8) shows me this tip:

> Unresolved variable or type SafariViewController require() call is missing less... (⌘F1) 
> Checks that all modules are referenced through "require()".
> Suggests inserting the "require()" call.
> Works only in files in the scope of "Node.js Core" JavaScript library.

Running Versions:

cordova 6.0
phonegap  6.0
AngularJS 1.4
Node.js 4.2.4

*NOT an Ionic FW project.

**Comment by davibertolini** [comment]
Terribly sorry. I just realized that such only occurs when running the app through PhoneGap's server (`$ phonegap serve`), but when building it and launching it with the emulator it works. Rookie mistake.

**Comment by EddyVerbruggen** [comment]
:+1: No worries. If you ever have any further trouble with this plugin just let me know.

**Comment by Manindarn** [comment]
Hello I'm facing same issue in SafariviewController, could you please help me one the same and highly appricated.
Error: Can't find variable: SafariViewController

Version:-
Cordova version: 7.1
iOS platform version: 4.1.0
