### ISSUE TITLE
Documentation - document that this plugin requires Cordova Android 7.0.0 or later

### ISSUE THREAD

**Issue by AndrWeisR** [EddyVerbruggen/cordova-plugin-safariviewcontroller#153]
CordovaInterface.getContext(), used in ChromeCustomTabPlugin.java, was only added in Cordova Android 7.0.0, so you should document that dependency, to save headaches.

**Comment by EddyVerbruggen** [comment]
Not sure who you're aiming this at, but the PRs are open.

**Comment by AndrWeisR** [comment]
I could PR... or you could just edit the Readme.md ;)

**Comment by EddyVerbruggen** [comment]
You can edit the document directly in the browser and Github manages the PR workflow for you.

**Comment by AndrWeisR** [comment]
OK, I did that.

**Comment by EddyVerbruggen** [comment]
Closed by #154
