### ISSUE TITLE
Use SafariViewController instead of WKWebView (iOS)

### ISSUE THREAD

**Issue by abardik** [EddyVerbruggen/cordova-plugin-safariviewcontroller#156]
Hello. Is it possible to use SafariViewController instead of main WKWebView in iOS? I need to use WebRTC in my app, but it's unavailable in WKWebView, so I have to use iosrtc plugin now. So, I tried this:
```
<plugin name="cordova-plugin-safariviewcontroller"/>
<preference name="CordovaWebViewEngine" value="SafariViewController"/>
```
but after splash screen is faded away there is nothing left (or maybe transparent, because I see my running app in task manager, can switch to it, but again - nothing or transparent).

Any advice?

Thanks.

**Comment by EddyVerbruggen** [comment]
No. That's not possible.
