### ISSUE TITLE
OK (done in French) Hitbox too small

### ISSUE THREAD

**Issue by Bouzmine** [EddyVerbruggen/cordova-plugin-safariviewcontroller#18]
I don't know if it's editable but I find that I often need to try 3-4 times before closing it. In contrary, in Feedly (which uses Safari View Controller), I never stumbled upon this (with the same fingers).

**Comment by EddyVerbruggen** [comment]
It's supposed to be the exact native component. There's nothing in the plugin related to this so it's default behaviour and afaik can't be changed.
