### ISSUE TITLE
Possibility to add referrer info

### ISSUE THREAD

**Issue by jvence** [EddyVerbruggen/cordova-plugin-safariviewcontroller#2]
Great plug-in. Working well.
Would it be possible to eventually specify a referral so that website would know that a specific app is driving traffic to them?
Thanks

**Comment by EddyVerbruggen** [comment]
Have you tried adding it? And what did and did not work for you?

**Comment by jvence** [comment]
Sorry but where would I add it? The plugin seems to only accept a URL and a readmode. I'm talking about a referral header that can be seen understood by all web servers.

**Comment by EddyVerbruggen** [comment]
You can't add custom headers. Were you able to do that with the in-app browser plugin?

**Comment by berndartmueller** [comment]
+1 I would also need this feature to ensure correct affiliate tracking :)

**Comment by EddyVerbruggen** [comment]
Please read about the limitations of the SafariViewController - we can only use what Apple's SDK has to offer: https://developer.apple.com/library/ios/documentation/SafariServices/Reference/SFSafariViewController_Ref/index.html#//apple_ref/occ/instp/SFSafariViewController/delegate
