### ISSUE TITLE
transition property seems to have no effect

### ISSUE THREAD

**Issue by rubenstolk** [EddyVerbruggen/cordova-plugin-safariviewcontroller#20]
No matter what I send for `{ animation: true, animation: 'curl' }`, it always seems to just slide.

**Comment by EddyVerbruggen** [comment]
Just found out that this has been changed by Apple in iOS 9.2 or 9.3. You can now swipe back to go back to your app, so I guess they now always slide 'forward' when presenting Safari so it's obvious to the user you can use the slide-back gesture.
