### ISSUE TITLE
Change statusbar text color to dark

### ISSUE THREAD

**Issue by ohh2ahh** [EddyVerbruggen/cordova-plugin-safariviewcontroller#22]
I changed the color of the statusbar in my app to white with the `cordova-plugin-statusbar` plugin. When the Stafari View Controller is opened, the statusbar keeps white and is therefore not readable. It would be great if you could check the statusbar color and adjust it if necessary.

Thanks for your plugin!

My workaround:
```js
// Success callback
function(result) {
  if(result.event === 'opened') {
    // Dark text for light background
    StatusBar.styleDefault();
  } else if(result.event === 'closed') {
    // Light text for dark background
    StatusBar.styleLightContent();
  }
}
```

**Comment by johnthepink** [comment]
@ohh2ahh I just tried to recreate your issue, and I can't seem to do it. I've created a simple repo here: https://github.com/johnthepink/safaritest

It sets the background to not overlay the webview in `config.xml`, then it sets the background color to green, and the text color to white in `www/index.html`. I'm getting this, respectively:

<img width="578" alt="screenshot 2016-05-31 23 26 41" src="https://cloud.githubusercontent.com/assets/816517/15697346/3a87a96c-2787-11e6-931b-2faf32257b8f.png">
<img width="578" alt="screenshot 2016-05-31 23 26 49" src="https://cloud.githubusercontent.com/assets/816517/15697349/3e2a75cc-2787-11e6-929b-5871bddbc1c0.png">
<img width="578" alt="screenshot 2016-05-31 23 27 04" src="https://cloud.githubusercontent.com/assets/816517/15697354/41f7392e-2787-11e6-8c66-b5790be0ba8d.png">

Could you help reproduce? Thanks!

**Comment by ohh2ahh** [comment]
@johnthepink Thank you very much for your effort! I've tested your sample application and it works. I totally forgot that I added manually the following properties to the app's plist. It changes the statusbar style already when the splash screen shows, but ufortunately, it also overwrites the plugin's adjustments. Sorry for my mistake...

```xml
<key>UIStatusBarHidden</key>
<false/>
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleLightContent</string>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

**Comment by johnthepink** [comment]
@ohh2ahh cool glad you figured it out. I guess this can be closed then?
