### ISSUE TITLE
Can I change text `Done` to any other?

### ISSUE THREAD

**Issue by kntmrkm** [EddyVerbruggen/cordova-plugin-safariviewcontroller#24]
I want to use this in japanese.

change text `Done` to `完了`.

Is it possible?

thanks.

**Comment by kntmrkm** [comment]
I found a setting. solved.

<img width="611" alt="filii_xcodeproj" src="https://cloud.githubusercontent.com/assets/2703486/15695970/2a6ca72a-27e7-11e6-9819-381df9626845.png">

**Comment by johnthepink** [comment]
@kntmrkm I just looked through the docs, and it doesn't look like the iOS SafariViewController class lets you set that text dynamically. Meaning, this plugin won't be able to implement that. The localization setting seems to be the right way :)

**Comment by EddyVerbruggen** [comment]
Cheers guys!
