### ISSUE TITLE
Issue with foreign characters

### ISSUE THREAD

**Issue by tabrindle** [EddyVerbruggen/cordova-plugin-safariviewcontroller#26]
This may be an edge case, but perhaps worth considering for multilingual apps. 

I occasionally have URLs to open that have unencoded Chinese characters in them, which when calling URLWithString will yield null. Passing this kind of URL to SafariViewController in this call - 

`[[SFSafariViewController alloc] initWithURL:url entersReaderIfAvailable:readerMode];` 

will cause an unhanded exception, and send no error message back to Cordova. 

A possible solution might be this:

`NSURL *url = [NSURL URLWithString:[urlString stringByAddingPercentEscapesUsingEncoding: NSUTF8StringEncoding]];`

I'm not sure about side effects, so we might consider this as an additional option that we can pass in the JavaScript `SafariViewController.show()` method call. At the very least we might consider a null check on the `NSURL *url` variable

**Comment by EddyVerbruggen** [comment]
Interesting issue. I agree we should attempt having the plugin fix it, but would it be possible to encode the URL in JS before sending it to the plugin? Do you have an example of a troublesome URL perhaps?

**Comment by tabrindle** [comment]
In my limited experience with this, the `encodeURI()` function in JS will also encode URIs encoded in query parameters, resulting in double encoding which won't work. (Think auth redirects on some sites, or partner store networks - http://example.com/auth?next=http%3A%2F%2Fexample.com%2Fpage) Some quick Googling showed me that both JS and Objective C have about a thousand ways of doing this, but this particular Objective C method doesn't seem to do anything but encode the foreign characters. If you have a better way to do this, I very open to it. 

Apologies for the strange/amusing [link](http://www.brasbh.com/ecommerce/內衣【小百合】b-c-d-側收副乳-深v聚攏-吸濕排汗-竹炭紗-雙軟條-機能調整型內衣-台灣製-nj9121.html?u1=ivenue), but it's the only functioning example I have. 

For what it's worth, I have [forked](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/compare/master...tabrindle:master) the project and added a check on the NSURL cast url variable, returning an error to cordova if the URL provided is bad. Seems to work with some bad urls I gave it, and the above test case.

**Comment by EddyVerbruggen** [comment]
Thanks for the fork, I've integrated it through a pull request. That's a lot better than it was 👍 

I'll keep this issue open so we can think about further enhancements. Perhaps try the `stringByAddingPercentEscapesUsingEncoding` in case the cast URL was `nil`, and fall back to the error handler in case it's still `nil` after trying that.

**Comment by HiteshPatadia** [comment]
is there any update on this? I am facing the same issue.
