### ISSUE TITLE
Status of Android support?

### ISSUE THREAD

**Issue by cvillerm** [EddyVerbruggen/cordova-plugin-safariviewcontroller#28]
Hi,
To my (good!) surprise, I figured out today that there is experimental (?) work done to have this work too on Android by using the equivalent Chrome Custom tabs features. I first saw the code and then a quick description in the wiki section.
Couldn't this be referred too directly in the main README page? Is there a plan to update this plugin to rename it to make it more agnostic of the underlying platform (something like "NativeInAppBrowser")?
In any case, this is (again) great work! You got a new star :) Thanks for this.
Claude

**Comment by yakirn** [comment]
Hey @cvillerm thanks for your feedback, and sorry for the late response.
Yes, the android platform of this plugin is experimental as in that it's API might change in the future. I consider it safe to use, but I recommend that you will wrap it with your own code, in case there will be changes. Also, I would test it better on older devices if that's a requirement for you.
Once we'll figure out the correct API that will serve both platforms well, and let it mature a bit, a rename will also be considered.

@EddyVerbruggen would you mind if I add a link to the WIKI from the readme?

**Comment by EddyVerbruggen** [comment]
@yakirn sorry for not seeing this earlier, I wouldn't mind.
