### ISSUE TITLE
Provide way to style bottom toolbar

### ISSUE THREAD

**Issue by aaronorosen** [EddyVerbruggen/cordova-plugin-safariviewcontroller#29]
This is really cool. I was wondering if it is possible to allow the user to style the bottom toolbar? Or would something like that not be possible?

i.e: here

![image](https://cloud.githubusercontent.com/assets/1063157/17087200/45d29348-51b9-11e6-8d80-0142b3e4915b.png)

For example, I'm currently using this: https://github.com/initialxy/cordova-plugin-themeablebrowser but would love to use this instead though the missing feature would be providing a way to style the bottom toolbar with my own images and also provide a hook in order to get callbacks to button presses via javascript. Would something like this be possible via the SafariViewController?

**Comment by johnthepink** [comment]
To my knowledge, styling the bottom toolbar or adding images is not possible with the Safari View Controller. This is a limitation of the native component. The only styling you can use is changing the tint color of the icons/text, shown here https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/blob/master/demo/index.html#L41

**Comment by aaronorosen** [comment]
Thanks for the reply @johnthepink  

Do you know how someone would go about building something similar to what facebook has built for their inappbrowser: 
![image](https://cloud.githubusercontent.com/assets/1063157/17123523/ea85a152-5298-11e6-8afa-1926482c6e8e.png)

Currently I'm playing around with  https://github.com/initialxy/cordova-plugin-themeablebrowser  but it seems to be very slow and doesn't let me insert two toolbars to style and doesn't show a url bar only page title :/

**Comment by johnthepink** [comment]
@aaronorosen I don't know of any cordova plugins that do what you are talking about out of the box, but there may be. It sounds like you may need to fork something like the themeablebrowser plugin and add the functionality that you want.
