### ISSUE TITLE
Allow plugin to work with Android

### ISSUE THREAD

**Issue by jvence** [EddyVerbruggen/cordova-plugin-safariviewcontroller#3]
Sounds crazy but it would be nice for the plug-in to work on Android by simply reverting to the default android browser. That way we don't have to do it programmatically.

**Comment by EddyVerbruggen** [comment]
Thanks for the idea but it's common practice to not support a platform in plugin.xml if it's not supported. 

After all, all you need to do is check for the `window.SafariViewController` object.

**Comment by jvence** [comment]
window.SafariViewController exists in android. Not enough to check for it.

**Comment by EddyVerbruggen** [comment]
Ah, fair point. I should have moved the JS clobbers inside the ios platform tags. Reopening!

**Comment by JaganC** [comment]
You can assign a empty variable, it does the job 
var SafariViewController;  i have using with iOS and Windows, it works as SVC on iOS 9 and works as InAppBrowser for other devices

**Comment by EddyVerbruggen** [comment]
Just merged a PR which should help with this. Part of 1.3.0 (just released).
