### ISSUE TITLE
Issue in iPad Pro

### ISSUE THREAD

**Issue by atifgulzar** [EddyVerbruggen/cordova-plugin-safariviewcontroller#31]
I have dummy project,
( only issue in iPad Pro )
Same url I open using this plugin, it open mobile responsive site for iPad Pro, But when I open it on safari it's work fine,
Please see attached screenshots

and for your testing here is the url I'm looking for
http://www.spotlightstores.com/nz/bed/bed-linen/duvet-covers/brampton-house-baruta-quilt-cover-set/p/BP80367341-yellow

![simulator screen shot 10-aug-2016 12 15 53 pm](https://cloud.githubusercontent.com/assets/572680/17545621/92ce9390-5ef7-11e6-8d48-8bb23e17cc32.png)
![simulator screen shot 10-aug-2016 12 16 01 pm](https://cloud.githubusercontent.com/assets/572680/17545622/92d6fd32-5ef7-11e6-8b36-27758d6c437c.png)

**Comment by EddyVerbruggen** [comment]
I can't help that.
