### ISSUE TITLE
build failed in android

### ISSUE THREAD

**Issue by ezazwar1** [EddyVerbruggen/cordova-plugin-safariviewcontroller#32]
Hi, the build failed with following exception in android by adding chrome-tabs @yakirn 

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'android'.
  
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not find com.android.support:customtabs:23.2.0.
  >  Searched in the following locations:
  >      https://repo1.maven.org/maven2/com/android/support/customtabs/23.2.0/customtabs-23.2.0.pom
  >      https://repo1.maven.org/maven2/com/android/support/customtabs/23.2.0/customtabs-23.2.0.jar
  >      file:/Users/ezazwar/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.pom
  >      file:/Users/ezazwar/Library/Android/sdk/extras/android/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.jar
  >      file:/Users/ezazwar/Library/Android/sdk/extras/google/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.pom
  >      file:/Users/ezazwar/Library/Android/sdk/extras/google/m2repository/com/android/support/customtabs/23.2.0/customtabs-23.2.0.jar
  >  Required by:
  >      :android:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by yakirn** [comment]
Hey @ezazwar1 
Sorry for the late response. but I can't reproduce your problem.
I also tried on a fresh project:
```
cordova create custom-tab-issue
cordova platform add android
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller
cordova build
```
succeeded.
I'm using:

- Cordova 6.1.1
- Android 5.1.1
- Java 8

What versions do you use?
It could be that there is additional configuration/installation required that I forgot to add to the wiki, has anyone else experienced this issue?

**Comment by yakirn** [comment]
Ok, Maybe this will help:
Open android studio and open the SDK manager, then go to the 'SDK Tools' tab, and check 'Android Support Repository' (I think you can also do it from the CLI if you don't use Android Studio).
When it's done installing retry to build.
This should apply to all of the projects you build on your machine.
Please tell me if that solved your issue so I will add it to the Wiki.

**Comment by mikeduarte** [comment]
I'm having build errors as well in Android.  Red x's next to com.customtabplugin and org.chromium.customtabsclient.shared

**Comment by mikeduarte** [comment]
In case anyone else runs into the same build problems:

1. Make sure you download the 'Android Support Repository' as yarkirn mentioned.
2. You need to manually add 2 libraries to your project listed below:

/extras/android/support/v7/appcompat/libs/android-support-v4.jar
/extras/android/support/customtabs/libs/android-support-customtabs.jar

Instructions on how to add the external libraries (choose the libraries above and not what is listed in the instructions from the link below):

http://stackoverflow.com/questions/18299898/the-import-android-support-cannot-be-resolved

**Comment by yakirn** [comment]
@mikeduarte the build should work without the second step as the plugin declares the dependancy  you mentioned in the plugin.xml file like this:
`<framework src="com.android.support:customtabs:23.2.0" />`
Cordova reads that and add edit the build.gradle file appropriately.

In Cordova projects editing your build.gradle as suggested in the link you gave file isn't a good idea IMO. As the file is auto-generated by Cordova, and your changes might get lost...

**Comment by mikeduarte** [comment]
@yakirn I don't know why it won't work for me without adding the libraries directly to the project, but I didn't edit the build.gradle file.  All I did was add the 2 libraries.  If I do not add them to the project, com.customtabplugin and org.chromium.customtabsclient.shared do not seem to find the appropriate support classes.

I see this in the build.gradle file:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.android.support:customtabs:23.2.0"
    // SUB-PROJECT DEPENDENCIES END
}
