### ISSUE TITLE
Just an FYI: 'Modernizing OAuth interactions in Native Apps for Better Usability and Security'

### ISSUE THREAD

**Issue by ChristianWeyer** [EddyVerbruggen/cordova-plugin-safariviewcontroller#34]
Sorry, this is not meant to be spam... ;-)

But I think this is important news:
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html?m=1

No longer support for classic 'web-views'.
Cheers!

**Comment by EddyVerbruggen** [comment]
Thanks, noted.
