### ISSUE TITLE
Incompatible with PhoneGap Build?

### ISSUE THREAD

**Issue by donrowlett** [EddyVerbruggen/cordova-plugin-safariviewcontroller#35]
Hi Eddy,

I would love to use your plugin, but I can't get it to work with build.phonegap.com.

I'm getting the error: "Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-safariviewcontroller".

I'll keep a watch here in case anything comes up that might help me.

Thanks!

**Comment by aboveo** [comment]
use this it worked for me

<gap:plugin name="cordova-plugin-safariviewcontroller" src="https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller.git#1.4.0" />

**Comment by EddyVerbruggen** [comment]
@donrowlett Which version do you use according to PhoneGap Build, and where do you install it from according to `plugin.xml`? If it's the latest from `npm` then please also include the build log PGB provides you (there's a button somewhere to show the build log which may reveal relevant info for solving the issue).

 @aboveo thanks for assisting.

**Comment by donrowlett** [comment]
Hey Eddy, I got it working using the code provided by aboveo. It helps to use a version number that actually exists...  silly me.  

Anyway, I thought you would like to know.

**Comment by donrowlett** [comment]
Ack.  I need ability to disable location bar and back buttons and such....  sad face.
