### ISSUE TITLE
Compile error on SDKs before iOS10

### ISSUE THREAD

**Issue by jrunkel** [EddyVerbruggen/cordova-plugin-safariviewcontroller#37]
The directive

`#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0 `

does not work as intended on XCode 7, as `__IPHONE_10_0 ` is not defined (yet) and therefore evaluates to 0. 

Please use numeric version identifier (i.e.: 100000) instead.

**Comment by EddyVerbruggen** [comment]
Xcode 7.3.1 didn't complain for me, but your change is fine, thanks!
