### ISSUE TITLE
SafariViewController in iOS 10

### ISSUE THREAD

**Issue by jamessharp** [EddyVerbruggen/cordova-plugin-safariviewcontroller#39]
Just an FYI really that as of iOS 10 safariviewcontroller cannot be hidden:

From https://developer.apple.com/app-store/review/guidelines/:

> SafariViewContoller must be used to visibly present information to users; the controller may not be hidden or obscured by other views or layers. Additionally, an app may not use SafariViewController to track users without their knowledge and consent.

Trying to do so just results in nothing happening. :(

**Comment by EddyVerbruggen** [comment]
Oh shoot! You confirmed that it did work in iOS 9 and doesn't in 10? Then I need to deprecate that property and update the doc..

**Comment by johnthepink** [comment]
@jamessharp Good catch. So we probably need a PR to update the docs at least.

**Comment by jamessharp** [comment]
Yup

**Comment by tabrindle** [comment]
Does this mean that passing cookie authentication in the background will no longer work?

**Comment by EddyVerbruggen** [comment]
A fix has been merged into master - I've seen it compiles fine and all seems good at runtime, but I'd be even happier if someone with a real need for this feature tests the current version on GitHub.

Thanks!
