### ISSUE TITLE
Question: Is it possible to get cookie information out of this plugin?

### ISSUE THREAD

**Issue by benmcmaster** [EddyVerbruggen/cordova-plugin-safariviewcontroller#4]
I am looking for a client side fingerprinting cookie process for deeplinking into my app.

These guys say it's possible with iOS 9's Safari View Controller:

http://stackoverflow.com/questions/15955798/ios-app-store-pass-parameters-in-store-download-link

"Then when the user opens your app, open up an invisible Safari View Controller in the background while you show a spinner. As soon as you can inspect the cookie and see the last link clicked, you can stop the spinner--it should be a very fast operation." 

Is this possible using this plugin?

**Comment by EddyVerbruggen** [comment]
Nope, not at this time. For one you can't 'show' it in the background.

**Comment by benmcmaster** [comment]
Thought so. Thanks!
