### ISSUE TITLE
Cross Window Communication

### ISSUE THREAD

**Issue by seesoe** [EddyVerbruggen/cordova-plugin-safariviewcontroller#41]
Is it possible to send data from a safari view window to the parent app?

I'm currently trying by providing a link with `appname:query-string` as a URL. When clicked the parent apps will get the data, but the safari view will freeze and it can't be closed. Bug?

Maybe postMessage or maybe something like this solution?
http://www.telerik.com/blogs/cross-window-communication-with-cordova's-inappbrowser

What functionality is expected from the safari view success handler?

**Comment by EddyVerbruggen** [comment]
Does the readme help you in the matter?

**Comment by seesoe** [comment]
actually ya i was able to figure it out, I got things to work perfectly. I think the app would freeze because an internal app redirect from login page to main page was taking place with safari view on top. I just called close before the redirect and it is great now. thanks for the great work on both plugins!
