### ISSUE TITLE
Hide/Disable address bar, safari icon

### ISSUE THREAD

**Issue by aggarwalankush** [EddyVerbruggen/cordova-plugin-safariviewcontroller#45]
Hi,

Is there any way to hide safari icon to prevent user to open url in native safari browser? Also, can we hide address bar content. I don't want user to know the url.

-Thanks

**Comment by gino8080** [comment]
same question

**Comment by darkyen** [comment]
> Is there any way to hide safari icon to prevent user to open url in native safari browser? Also, can we hide address bar content. I don't want user to know the url.

That sounds ridiculously suspicious! I am curious what is the use-case here?

**Comment by EddyVerbruggen** [comment]
Nope

**Comment by Naveendodda** [comment]
For me also same requirement . we want hide address bar means user don't see the url .Please help how to achieve this one . Please suggest me
