### ISSUE TITLE
Sound keeps on playing in safari view controller from a video even if the safari view controller is closed using Done button

### ISSUE THREAD

**Issue by vivekpd15** [EddyVerbruggen/cordova-plugin-safariviewcontroller#46]
Hi,

I am facing this issue where the sound keeps on playing in safari view controller from a video even if the safari view controller is closed using the Done button on iOS. I am using the latest version of this plugin along with wkwebview, and running on iOS 10.

Any help would be greatly appreciated.

Thanks.

**Comment by EddyVerbruggen** [comment]
Intersting case. Can you try without wkwebview to get that out of the equation?

**Comment by vivekpd15** [comment]
I tried it on an iPhone 5 running iOS 10 without the wkwebview plugin. The results were the same.

Any idea what's going around here?

**Comment by EddyVerbruggen** [comment]
If you close it with the 'Done' button then it must be a problem in iOS itself as there's nothing that the plugin does to prevent SVC from closing when that button is pressed. Perhaps Google it and/or file a Radar with Apple?

**Comment by larssn** [comment]
I think it's safe to close this issue at this point.

**Comment by ramohanreddy** [comment]
Hi @larssn 
I am also facing same issue  can you pls tell me the solution.

Thanks&Regards
Ramohan Reddy
