### ISSUE TITLE
Does not work in Phonegap Developer App

### ISSUE THREAD

**Issue by jlchereau** [EddyVerbruggen/cordova-plugin-safariviewcontroller#50]
Any reason why this plugin does not work in Phonegap Developer App considering builds produced by Phonegap Build work as expected?

My config at https://github.com/kidoju/Kidoju-Mobile/blob/master/config.xml

**Comment by EddyVerbruggen** [comment]
If it's not in the list of plugins bundled with the developer app then it won't work.

**Comment by jlchereau** [comment]
How could I have missed it? Feeling stupid. Thx not only for your kind answer but also for all your plugins.

**Comment by EddyVerbruggen** [comment]
It's a common thing to overlook, no worries
