### ISSUE TITLE
Support for upcoming iPhone X

### ISSUE THREAD

**Issue by Hirbod** [EddyVerbruggen/cordova-plugin-safariviewcontroller#78]
Hi,

currently the View isn't optimized for the upcoming iPhone X. There are white bars at the top (you can try to test inside Simulator).

Would be nice to have support till 3th november, when iPhone X is going to land

**Comment by Hirbod** [comment]
@EddyVerbruggen my iPhone X just arrived today, and I've optimized my app for it but that plugin still does not look good on iPhone X. Could you maybe dig into this?

I used this answer to make my app look good on iPhone X.
https://stackoverflow.com/questions/46232812/cordova-app-not-displaying-correctly-on-iphone-x-simulator

**Comment by EddyVerbruggen** [comment]
I'm not sure what this plugin should do differently to support iPhone X?

**Comment by Hirbod** [comment]
Hi Eddy, looks like this plugin is just working fine in most cases, but if you have removed status bar on iPhone X it looks like this: (while looking perfectly fine on the other devices)

![1432046a-838a-4de0-81c2-5e301ccc155e](https://user-images.githubusercontent.com/504909/33125330-5ab02014-cf80-11e7-9ec2-d13d115bbc75.png)

**Comment by Hirbod** [comment]
FYI: there is a big gap on top

**Comment by EddyVerbruggen** [comment]
I understand, but there's not likely anything the plugin can do to influence that. But SO / Google may tell us otherwise.

**Comment by Hirbod** [comment]
I guess I will need to handle that statusbar issue myself (enabling on iPhone X).

Sorry for that false alarm.
