### ISSUE TITLE
is it possible to request "the desktop version" of the site? 

### ISSUE THREAD

**Issue by osterland** [EddyVerbruggen/cordova-plugin-safariviewcontroller#82]
Hiho folks,  

first of all ty eddy for another very helpful cordova plugin. 

I love that it is possible to request a "reader" version of the sites, and if was wondering if its also possible to get the desktop version of a site. 

any ideas? 

thanks!

**Comment by EddyVerbruggen** [comment]
Hi!

Unfortunately we can only do [what Apple allows us to do](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller), and that's not one of the things.

Frankly, Apple even decided to [deprecate support for loading a site in reader mode](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/1621221-init) (see the red label on the right).
