### ISSUE TITLE
Passing Cookies onto the ViewController

### ISSUE THREAD

**Issue by RDalziel** [EddyVerbruggen/cordova-plugin-safariviewcontroller#83]
If i have cookies already available in my cordova app, how can i ensure they are passed onto the SafariViewController?

Currently InAppBrowser seems to do this by default

**Comment by EddyVerbruggen** [comment]
SafariVC uses the cookies of the *system* browser..

**Comment by RDalziel** [comment]
@EddyVerbruggen  Is there no way to have these passed on?
