### ISSUE TITLE
After pressing "Done" on iOS in landscape orientation on iPhone 6S, the view is blank/white

### ISSUE THREAD

**Issue by CookieCookson** [EddyVerbruggen/cordova-plugin-safariviewcontroller#85]
Bit of a strange bug here. I've tested it across a couple of devices here and can only reproduce it on an iPhone 6S running iOS 11.

If you use this plugin to open and close a page in portrait orientation, it works fine. If you try it in landscape it loads the page, and when you return to the view back with your main application in it is completely white.

If you wait for a couple of seconds or trigger an orientation change it then catches up and renders correctly. However, if you start interacting with the blank view (in my circumstance) you get a blank white scrollable page which is the width of the height of the view (something to do with a standard portrait sized webview perhaps?) and from that point it won't re-render. You then have to go back to the home screen and re-enter the app for it to then render correctly (Triggering a pause/resume event).

I've had other reports of the same issue happening from users on the iPad Pro, not sure what OS version or orientation the device was held in.

![nov-14-2017 11-55-18](https://user-images.githubusercontent.com/3473396/32778673-b4fb5736-c932-11e7-8bb9-68e3116f388e.gif)

**Comment by dtc7240** [comment]
It happens exactly as described above on an iPad Pro running 10.3.3 as well.

**Comment by dtc7240** [comment]
It's a bit of a hack, but utilizing the cordoba-plugin-screen-orientation plugin, I was able to force my way through the issue by plugging the following into Eddy's example code:
`						// this success handler will be invoked for the lifecycle events 'opened', 'loaded' and 'closed'
						function(result) {
							if (result.event === 'opened') {
								// console.log('opened');
							} else if (result.event === 'loaded') {
								// console.log('loaded');
							} else if (result.event === 'closed') {
								// console.log('closed');
								setTimeout( function() {
									currentOrientation = screen.orientation.type;
									if ( currentOrientation.indexOf("landscape") >= 0 ) {
										screen.orientation.lock('portrait');
										screen.orientation.lock('landscape');
									} else {
										screen.orientation.lock('landscape');
										screen.orientation.lock('portrait');
									}
									screen.orientation.unlock();
								}, 500);
							}
						},
`

**Comment by CookieCookson** [comment]
Hey @dtc7240 thanks for your input! I think I have come across a similar issue but with another plugin. Check out this thread: https://issues.apache.org/jira/browse/CB-12141

**Comment by dtc7240** [comment]
Hey @CookieCookson, thanks a million!!  By the time I saw your response 6 days later and checked the statusbar issue you linked above, that issue had been resolved by statusbar v2.4.0 just 22hrs earlier.  I popped statusbar 2.4.0 in and the issue from this thread is now gone!!!!  No more silly flopping the screen orientation back and forth in front of the user ... thank you so much for the research and the heads up!

And thanks as always to @EddyVerbruggen for EVERYTHING he does in the Cordova community!!

**Comment by CookieCookson** [comment]
@dtc7240 Sounds great! I'll give it a go here and update the thread if it solves things my end.

**Comment by CookieCookson** [comment]
I can confirm that upgrading to `cordova-plugin-statusbar@2.4.0` solves the issue above 🎉
