### ISSUE TITLE
Close event callback

### ISSUE THREAD

**Issue by berndartmueller** [EddyVerbruggen/cordova-plugin-safariviewcontroller#9]
Hello Eddy,

first of all I want to thank you for all the effort you put in your cordova plugins. They are all working like a charm :)

I have just a simple feature request. Could you please implement a close callback to the safari view controller, so when a user clicks the "Done" button, I can listen to this event and execute custom code. That would be great!

Thank you,

Bernd

**Comment by EddyVerbruggen** [comment]
Hey Bernd, thanks!

And yes, that should be possible - there seems to be a relevant event in the SVC delegate.

**Comment by andreatondo** [comment]
+1

**Comment by EddyVerbruggen** [comment]
Hey guys, see the readme for the new features in 1.2.0. :sunglasses: :sparkles:
