### ISSUE TITLE
Encoding URLs

### ISSUE THREAD

**Issue by thomasmarren** [EddyVerbruggen/cordova-plugin-safariviewcontroller#91]
I noticed in a recent [PR](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/pull/68) that you added URL encoding to the url passed into the `show` method. This has caused breaking changes to two instances of authentication using safariViewController. Authentication callbacks tend to already be encoded and safariViewController is then double encoding them.

Would it be possible to make url encoding an optional parameter that can be passed into the `show` action? Or is there another option we have to prevent this plugin from forcing url encoding?

**Comment by ccorcos** [comment]
I can verify this.

**Comment by EddyVerbruggen** [comment]
Thanks guys, both of you, for sharing a fix! 1.5.2 is now live on npm 👌🏻
