### ISSUE TITLE
TypeError: Cannot read property 'open' of undefined"

### ISSUE THREAD

**Issue by acatalina** [EddyVerbruggen/cordova-plugin-safariviewcontroller#94]
Hi,

I am having some issues while running safariviewcontroller with android < 6.0.1 ... I have seen similar issues around and tried what worked for them but no luck at all and it is driving me absolutely mad hehe

```
12-12 09:04:43.023  3367  3367 D SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 313 : Error in Success callbackId: SafariViewController737894751 : TypeError: Cannot read property 'open' of undefined
12-12 09:04:43.023  3367  3367 I chromium: [INFO:CONSOLE(313)] "Error in Success callbackId: SafariViewController737894751 : TypeError: Cannot read property 'open' of undefined", source: file:///android_asset/www/cordova.js (313)
12-12 09:04:43.028  3367  3367 D SystemWebChromeClient: file:///android_asset/www/static/js/main.19f749b8.js: Line 1 : Uncaught (in promise) TypeError: Cannot read property 'open' of undefined
12-12 09:04:43.028  3367  3367 I chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read property 'open' of undefined", source: file:///android_asset/www/static/js/main.19f749b8.js (1)
```

I am running a cordova app (v 7.1.0, android v 6.3.0, ios v 4.5.3) with safarviewcontroller (v 1.5.2) and customurlscheme (v 4.3.0) using these to implement auth0 authentication. 

I have ```<preference name="AndroidLaunchMode" value="singleTask" /> ``` on my config.xml.

One of the solutions in a similar issue was installing inAppBrowser plugin. It does actually solves the TypeError but then I run into "unknown url scheme" :S 

Any ideas? Many thanks! :)

### Update

I have been messing around with it and after installing inAppBrowser plugin and installing Chrome in the device is working ¬¬ I saw a suggestion in the wiki about installing Android Support Repository and installing the master of the repo but that didn't work for me although installing Chrome did...

Any different solutions that force people to install chrome? XD

**Comment by Farmin1** [comment]
> Hi,
> 
> I am having some issues while running safariviewcontroller with android < 6.0.1 ... I have seen similar issues around and tried what worked for them but no luck at all and it is driving me absolutely mad hehe
> 
> ```
> 12-12 09:04:43.023  3367  3367 D SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 313 : Error in Success callbackId: SafariViewController737894751 : TypeError: Cannot read property 'open' of undefined
> 12-12 09:04:43.023  3367  3367 I chromium: [INFO:CONSOLE(313)] "Error in Success callbackId: SafariViewController737894751 : TypeError: Cannot read property 'open' of undefined", source: file:///android_asset/www/cordova.js (313)
> 12-12 09:04:43.028  3367  3367 D SystemWebChromeClient: file:///android_asset/www/static/js/main.19f749b8.js: Line 1 : Uncaught (in promise) TypeError: Cannot read property 'open' of undefined
> 12-12 09:04:43.028  3367  3367 I chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read property 'open' of undefined", source: file:///android_asset/www/static/js/main.19f749b8.js (1)
> ```
> 
> I am running a cordova app (v 7.1.0, android v 6.3.0, ios v 4.5.3) with safarviewcontroller (v 1.5.2) and customurlscheme (v 4.3.0) using these to implement auth0 authentication.
> 
> I have `<preference name="AndroidLaunchMode" value="singleTask" /> ` on my config.xml.
> 
> One of the solutions in a similar issue was installing inAppBrowser plugin. It does actually solves the TypeError but then I run into "unknown url scheme" :S
> 
> Any ideas? Many thanks! :)
> 
> ### Update
> I have been messing around with it and after installing inAppBrowser plugin and installing Chrome in the device is working ¬¬ I saw a suggestion in the wiki about installing Android Support Repository and installing the master of the repo but that didn't work for me although installing Chrome did...
> 
> Any different solutions that force people to install chrome? XD

Hi, did u ever solve this? I'm getting the same problem.

**Comment by WuglyakBolgoink** [comment]
@Farmin1 try to reinstall plugin and platform. sometimes this help too.
