### ISSUE TITLE
Assets like cookies are not shared anymore.

### ISSUE THREAD

**Issue by artyom-dorokhov** [EddyVerbruggen/cordova-plugin-safariviewcontroller#95]
Since iOS 11 Safari and other apps get their own cookies and website data.

This means that cookies, local storage, and other browsing data will be contained within your app and scoped to your app. And this means that the user won't automatically be logged in to whatever accounts they were logged into in Safari. What this does is it will prevent cross-app tracking of user's browsing activity that you and your users may not have even been aware about. And ultimately, it helps keep users' browsing activity private and scoped within your app.

https://developer.apple.com/videos/play/wwdc2017/225

So the following point of "Advantages over InAppBrowser" section is not valid anymore:
"Since this is the system's main browser, assets like cookies are shared with your app, so the user is still logged on in his favorite websites."

**Comment by EddyVerbruggen** [comment]
Thanks! This could have been a PR really :)

**Comment by artyom-dorokhov** [comment]
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller/pull/96
